apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  project: default
  source:
    path: charts/argo-cd
    repoURL: https://github.com/tron4x/argo-helm-appset.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
